# Generated by Django 4.1.1 on 2022-10-23 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=120)),
                ("unique_id", models.CharField(max_length=25)),
                ("name", models.CharField(max_length=120)),
                ("avatar_url", models.URLField(blank=True, null=True)),
                ("url", models.URLField()),
                ("location", models.CharField(blank=True, max_length=250, null=True)),
                ("email", models.CharField(blank=True, max_length=250, null=True)),
                ("bio", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "twitter_username",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("followers", models.IntegerField()),
                ("following", models.IntegerField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Starred",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_id", models.CharField(max_length=25)),
                ("url", models.URLField()),
                ("name", models.CharField(max_length=120)),
                ("owner", models.CharField(max_length=120)),
                ("owner_url", models.URLField()),
                ("description", models.CharField(max_length=150)),
                ("clone_url", models.URLField()),
                ("language", models.CharField(max_length=50)),
                ("forks", models.IntegerField()),
                ("visibility", models.CharField(max_length=25)),
                ("watchers", models.IntegerField()),
                ("license", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("open_issues", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="starred",
                        to="github.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_id", models.CharField(max_length=25)),
                ("url", models.URLField()),
                ("name", models.CharField(max_length=120)),
                ("description", models.CharField(max_length=150)),
                ("clone_url", models.URLField()),
                ("language", models.CharField(max_length=50)),
                ("forks", models.IntegerField()),
                ("visibility", models.CharField(max_length=25)),
                ("watchers", models.IntegerField()),
                ("license", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("open_issues", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositories",
                        to="github.profile",
                    ),
                ),
            ],
        ),
    ]
