# Generated by Django 4.1.1 on 2022-10-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="starred",
            name="description",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="starred",
            name="language",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
