# Generated by Django 4.1.1 on 2022-10-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github", "0003_alter_repository_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="language",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
